---
title: On Generalizing Ordered Cumulative Regression Models
date: '2016-11-05'
author:
- Robert W. Walker
categories:
- gen-ord-logit
citation:
  type: article-journal
  container-title: Journal of Modern Applied Statistical Methods
  publisher: Unpublished
  pdf-url: https://digitalcommons.wayne.edu/cgi/viewcontent.cgi?referer=https://www.google.com/&httpsredir=1&article=2061&context=jmasm
links:
- text: PDF
  icon: file-pdf
  href: https://digitalcommons.wayne.edu/cgi/viewcontent.cgi?referer=https://www.google.com/&httpsredir=1&article=2061&context=jmasm
---

## Abstract

We examine models that relax proportionality in cumulative ordered regression  models. Something fundamental arising from ordered variables and stochastic ordering implies a partitioning. Efforts to relax proportionality also relax the ability to collapse an inherently multidimensional problem to a partitioning of the (unidimensional) real line. It is surprising and  unfortunate  to  find  that  deviations  from  proportionality  are  sufficient  to  generate internal contradictions; undecidable propositions must exist by relaxing proportional odds without other relevant and significant changes in the underlying model. We prove a single theorem linking continuous support and partitions of a latent space to show that for these two characteristics to be simultaneously satisfied, the model must be the proportional-odds model. Conditioning on the adjacency that is closely related to the partitioning is fruitful, but at this point we join the class of continuation-ratio models. Alternatively, Anderson’s (1984) stereotype model is quite general and nests ordered and unordered choice models, but  again  we  have  left  the  domain  of  cumulative  models.  Adopting  multidimensional cumulative models or imposing covariate-specific thresholds are the only certain methods for avoiding these troubles  in the  cumulative  framework.  It  is  generically  impossible  to generalize the cumulative class of ordered regression models in ways consistent with the spirit of generalized cumulative regression models. Monte Carlo studies also demonstrate the general principles.

