---
title: 'Unpacking civic participation: Analyzing trends in black [and white] participation
  over time'
date: '2009-12-02'
author:
- Valeria S. Chapman
- Robert W. Walker
- Daniel Q. Gillion
categories: []
citation:
  type: article-journal
  container-title: Electoral Studies
  publisher: Unpublished
  pdf-url: https://www.sciencedirect.com/science/article/pii/S0261379409000560
links:
- text: PDF
  icon: file-pdf
  href: https://www.sciencedirect.com/science/article/pii/S0261379409000560
---

## Abstract

Differences in levels of political engagement between blacks and whites have long captured scholars' interest. As a consequence, this topic has been heavily studied in American politics. However, many of these studies have taken a static approach to analyzing political behavior and few have examined how individuals orient themselves to political participation over time. Yet, engagement in political behavior as well as the information that can be obtained from any specific political action will change within a mutable political environment. In our examination of patterns in blacks' and whites' political engagement between 1973 and 1994, we investigate the ability of various civic activities to differentiate between high and low propensity participators. This dynamic analysis, with the incorporation of a unique methodological approach, reveals a gradual increase in blacks' likelihood to engage in politics. Moreover, the increase in blacks' engagement has served to diminish racial disparities in political behavior over time.

