---
title: 'Overcoming equivocality on projects in the fuzzy front end: Bringing social
  networks back in'
date: '2018-12-02'
author:
- Polly S. Rizova
- Elliot N. Maltz
- Samir Gupta
- Robert W. Walker
categories: []
citation:
  type: article-journal
  container-title: Technovation
  publisher: Unpublished
  pdf-url: https://doi.org/10.1016/j.technovation.2018.05.006
links:
- text: PDF
  icon: file-pdf
  href: https://doi.org/10.1016/j.technovation.2018.05.006
---

## Abstract

The management of the fuzzy front end (FFE) phase of innovation is crucial to the ultimate success of new product and process initiatives. A critical challenge that teams face at this stage is dealing with equivocality – the extent to which project participants grapple with multiple, and plausibly conflicting, meanings and interpretations of the information available to them (Daft and Lengel, 1986; Weick, 1979). While initially, a certain level of equivocality is beneficial for enhancing team creativity and preventing early closure, at some point it must be resolved in order for an idea to become a viable New Product Development (NPD) project. This study employs a social networks perspective to understand how different types of informal work-based relations and their structural properties affect equivocality on project teams in the FFE. In particular, it examines the structural effects of two types of social relations and their associated networks -- technical-advice and friendship ties. The findings suggest that while high density in a projects technical-advice network is likely to reduce equivocality, high density in a projects friendship network is likely to increase it. More interestingly, having multiple members on projects who are highly central in the lab technical-advice network tends to increase equivocality unless it is balanced with members who occupy positions of high centrality in the lab friendship network. In addition to contributing to the scholarship on NPD, FFE, and social networks, the results offer managerial insights for deploying social networks in order to assemble NPD teams and structure the flows of communication on projects so as to resolve equivocality in the FFE.

