---
title: Management Practices and State Bond Ratings
date: '2010-12-02'
author:
- Skip Krueger
- Robert W. Walker
categories:
- bond-ratings
citation:
  type: article-journal
  container-title: Public Budgeting & Finance
  publisher: Unpublished
  pdf-url: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.929.5762&rep=rep1&type=pdf
links:
- text: PDF
  icon: file-pdf
  href: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.929.5762&rep=rep1&type=pdf
---

## Abstract

One of the central claims of public administration is that management matters for the performance of public entities. Quantifying the impact of organizational management is thus central to the empirical evaluation of this claim. Utilizing novel features of the Government Performance Project (GPP), we assess the impact of state‐level management practices on the credit quality of US states. The central challenge—that both the GPP data and bond ratings take the form of ordinal grades—suggests a common solution utilizing multiple indicators of a latent construct (management capacity and credit quality) with appropriate measurement models. After describing the characteristics of the measurement approach, we derive management capacity scores from the GPP data and credit quality scores using bond ratings from the three rating agencies. These derived scores then allow us to test linkages between credit quality of the US states and broad aspects of their relative management capacity. On the whole, we show that financial management capacity influences credit quality, while the evidence is less clear that other forms of management capacity matter.

