---
title: 'The Cost of Boosterism: Economic Development, Growth Management, and Municipal
  Bond Ratings'
date: '2010-09-01'
author:
- Skip Krueger
- Christopher V. Hawkins
- Robert W. Walker
categories:
- bond-ratings
citation:
  type: article-journal
  container-title: Municipal Finance Journal
  publisher: Unpublished
  pdf-url: http://www.civicresearchinstitute.com/online/PDF/The%20Cost%20of%20Boosterism:%20Economic%20Development,%20Growth%20Management,%20and%20Municipal%20Bond%20Ratings.pdf
links:
- text: PDF
  icon: file-pdf
  href: http://www.civicresearchinstitute.com/online/PDF/The%20Cost%20of%20Boosterism:%20Economic%20Development,%20Growth%20Management,%20and%20Municipal%20Bond%20Ratings.pdf
---

## Abstract

The battles playing out in local governments across America over development and growth management have important long-term implications that are often difficult to measure because of the long lag between policy decisions and the consequences of those decisions. This study suggests one way of investigating the long-term effects of policy decisions in the area of growth management. The consequences of development and growth management policies should be of great interest to those who invest in the debt issued by a community because it is the value of property that provides the underlying guarantee of that debt. One might assume that aggressive development is good for investors because a larger tax base increases the size of the underlying asset guaranteeing the debt, but borrowing from the dominant model in the investment literature on asset pricing, this article suggests that investors are significantly concerned with the future variability in the value of an investment. Future change, therefore—or at least the possibility of change—represents a risk for investors, a risk that is manifested in lower bond ratings and ultimately in higher interest costs on a jurisdiction’s debt. Support for this notion is illustrated in a test on a sample of cities in Massachusetts.

